description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^1.0.5"
  path_drawing: "^1.0.0"
  flutter: 
    sdk: "flutter"
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  printing: ^5.9.1
  pdf: ^3.8.1
  path_provider: ^2.1.0
  open_file: ^3.2.1
  google_fonts: ^2.1.0
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Montserrat"
      fonts: 
        - 
          asset: "fonts/Montserrat-700.ttf"
          style: "normal"
          weight: 700
  uses-material-design: true
