// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhQH747SC57FTuY4mcKx_Ts7KtQSa8sgU',
    appId: '1:1082677791427:web:8b98397fc8ec8da51db076',
    messagingSenderId: '1082677791427',
    projectId: 'cakebossbd',
    authDomain: 'cakebossbd.firebaseapp.com',
    storageBucket: 'cakebossbd.appspot.com',
    measurementId: 'G-9Z5ZZZWQ9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJMQuHxie8xaXuyWVh6G4qP1wDjBiBMkQ',
    appId: '1:1082677791427:android:80e5c273bba865381db076',
    messagingSenderId: '1082677791427',
    projectId: 'cakebossbd',
    storageBucket: 'cakebossbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtHF9WxVeHs2LD8WNRQOjC7BNvO8366cY',
    appId: '1:1082677791427:ios:2f5a518bb0f4849c1db076',
    messagingSenderId: '1082677791427',
    projectId: 'cakebossbd',
    storageBucket: 'cakebossbd.appspot.com',
    iosClientId: '1082677791427-bovpa0tg778q6ii8m28idi0lg7f8fad4.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
